### ISSUE TITLE
KeyError while loading question

### ISSUE THREAD

**Issue by digitalyours** [DIRKMJK/limepy#11]
I'm a little bit lost and maybe I'm missing something, while initializing some questions I receive a "KeyError". I'm still new to Python, maybe it is something obvious I have overlooked.

**Comment by DIRKMJK** [comment]
Hi, just checking: did you manage to create a Survey object? And using this object, did you manage to access the question list? And did you try to create the Question object using the question id from the index of the question list?

**Comment by digitalyours** [comment]
Yes, to all the questions above. I'm using the ID and it fails for certain questions only. If you want I could (privately) share my dataset & questionnaire.

**Comment by DIRKMJK** [comment]
Yes, that might be helpful. Do you have an email address where I could contact you?

**Comment by digitalyours** [comment]
yep, I'm reachable at christoph {at} rechsteiner [.] de

**Comment by DIRKMJK** [comment]
For reference: the solution was to use the following settings when exporting the data: set <code>Headings / Export questions</code> to <code>Question code</code> and <code>Responses / Export responses as</code> to <code>Answer codes</code>
