### ISSUE TITLE
user_id unclear in documentation

### ISSUE THREAD

**Issue by bbo2adwuff** [DIRKMJK/limepy#14]
Sorry but I am not sure what to enter for `user_id`?

I can use the login on my base url and visit `index.php/admin/remotecontrol`.

I tried to enter my username twice:

```python
from limepy import download

download.get_session_key(
    base_url,
    "my_username",
    "my_pw",
    "my_username",
)
```
But I just get:
```js
{'id': "my_username'', 'result': {'status': 'Invalid user name or password'}, 'error': None}
```

I'm sure that I entered the username and pw correctly as they are the same as for the login via base url + `/admin`, right?

As I wasn't able to find anything related to an `user_id` on https://api.limesurvey.org/classes/remotecontrol_handle.html or on https://manual.limesurvey.org/RemoteControl_2_API#Python_example_and_glue

Maybe a small note on the README page could be helpful for new users?

**Comment by DIRKMJK** [comment]
Hi, if you log into Limesurvey and go to Configuration / Manage Survey Administrators, you can look up the User ID. My advice would be to create a new user specifically for accessing the API, and grant this user only the relevant permissions. Hope this helps! I’ll update the Readme later on

**Comment by bbo2adwuff** [comment]
Thanks! Now I get it. I was logged in already as the new user and thought that I'll find my `user_id` somewhere there.

I planned to write a little script using your package so that our users can type in their username and password and then the script works. But it seems they have to ask me first for their `user_id`? So the followup question would be isn't it possible without the `user_id` as these examples [here](https://manual.limesurvey.org/RemoteControl_2_API#Python_example_and_glue) don't seem to require one?

**Comment by bbo2adwuff** [comment]
Oh maybe these example actually do need the `user_id`? In the examples there seems to be always an `id` set to `1`...

**Comment by DIRKMJK** [comment]
I guess admin usually has id 1, so if people using your script are always using their admin password, I suppose you could hard code `user_id=1`

**Comment by bbo2adwuff** [comment]
@DIRKMJK Thanks a lot for your answers!

> if people using your script are always using **their admin password**, I suppose you could hard code `user_id=1`

Unfortunately not.

But well this is obviously not an issue of your package, but of the API itself. So I'll close this issue.
Thanks for providing this nice package ;)
