### ISSUE TITLE
some open ended questions are just empty

### ISSUE THREAD

**Issue by daniel-ratz** [DIRKMJK/limepy#18]
Hi,
first of all, thanks for your amazing library, it helps me a lot for my bachelors thesis.
But i noticed one problem: some questions dont work with the write_open_ended function.
The question itself gets written but without answers.
As of right now i cannot figure out why that happens, but i'll take a look.
If i print the corresponding df everything looks fine and not different from questions that gets written properly.

Any ideas?

**Comment by daniel-ratz** [comment]
Ok, i found something, it seems like the column indices arent detected properly if self.metadata['other'] is true.
if i just hardcode the indice everything works fine. But that doesnt tell me why some questions are working, and some are not. But at least i can continue now.

**Comment by DIRKMJK** [comment]
Hi Daniel, thanks for your feedback! What question type did you get this problem with?

**Comment by daniel-ratz** [comment]
> Hi Daniel, thanks for your feedback! What question type did you get this problem with?

Short free text.

it seems like its really the missing index, if i print the corresponding column_ indice its just empty.
is this a problem with my .csv/.lss or limepy? i could send you a stripped but bugged dataset in private.

for example:
`question1: [10]
question2: [12]
question3: []
question4: []`

question3 & question4 wouldnt have any answers written into the .md file

**Comment by DIRKMJK** [comment]
I didn’t get the same problem with this question type. Perhaps it’s something to do with the version of Limesurvey; what version are you using?

**Comment by daniel-ratz** [comment]
im using version Version 5.2.4+211129.
i also dont have problems with every "short free text" question, just some questions, but always the same.

out of 10 questions, 2 dont work.

**Comment by DIRKMJK** [comment]
I find it intriguing that this happens with some questions, but not others. I suspect this may have something to do with the .lss file. Do you think you could share that file, here or via feedback@dirkmjk.nl?
