### ISSUE TITLE
Unable to use Plugin for authentication

### ISSUE THREAD

**Issue by Shnoulle** [DIRKMJK/limepy#19]
When try to connect with LDAP authentication : you ca n not set Plugin param

See : https://manual.limesurvey.org/RemoteControl_2_API#get_session_key

**Comment by Shnoulle** [comment]
Same workaround : https://github.com/DIRKMJK/limepy/issues/21
work 
Adding & or ? after the complete url.

**Comment by DIRKMJK** [comment]
Do I understand correctly that the `plugin` param is an optional parameter? And that the solution would be to add an optional paramter `plugin` to the `get_responses` and `get_session_key` functions and that, if provided, this `plugin` param should be added to the list of params sent with the request in the `get_session_key` function?
