### ISSUE TITLE
Did not work out of apache (deafult nginx or IIS)

### ISSUE THREAD

**Issue by Shnoulle** [DIRKMJK/limepy#21]
The url set is OK only if you use apache.

Not with IIS or nginx server (it's /index.php?r=admin/remotecontrol )

**Workaround** : set the url to `https://example.org/limesurvey/index.php?r=admin/remotecontrol&`

Maybe an option to avoid the workaround ?

**Comment by DIRKMJK** [comment]
I wasn't aware that the url used doesn't work with non-Apache servers. Is the workaround url you suggest supposed to work with Apache as well? I got a bad request error when I tried to use it
