### ISSUE TITLE
`TypeError: string indices must be integers` in wrangle.py

### ISSUE THREAD

**Issue by philipstr01** [DIRKMJK/limepy#22]
While trying to build a simple pipeline, I encountered an error that I can't seem to fix on my end.
The error being raised:
`/python3.10/site-packages/limepy/wrangle.py", line 134, in <dictcomp>
    if item['language'] == language`
`TypeError: string indices must be integers`

The section of code mentioned:
```
            if not isinstance(items, list):
                items = [items]
            question_l10ns = {
                item['qid']:item['question']
                for item
                in items
                if item['language'] == language
```

My code can be found [here](https://github.com/philipstr01/teamnotional-ixd).

**Comment by DIRKMJK** [comment]
Hi, do you think you could share the .lss file? And the version number of the Limesurvey installation?

**Comment by philipstr01** [comment]
Thank you so much for answering, here is the [.lss file](https://github.com/philipstr01/teamnotional-ixd/blob/main/raspy/data/structure.lss ).
And I did not install limesurvey but the version in my of my site is 5.4.12

**Comment by DIRKMJK** [comment]
Thanks, I think I found the problem. Could you upgrade limepy and try if it works now?

**Comment by philipstr01** [comment]
sorry for the late response! Thank you so much. Everything works fine now :)
