### ISSUE TITLE
download.get_responses(base_url, user_name, password, user_id, sid) error

### ISSUE THREAD

**Issue by AmauryVanEspen** [DIRKMJK/limepy#24]
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
[<ipython-input-47-d45c49986ebc>](https://localhost:8080/#) in <module>
      8 sid = '156133'
      9 
---> 10 csv = download.get_responses(base_url, user_name, password, user_id, sid)
     11 path = Path('../data/responses.csv')
     12 path.write_text(csv)

5 frames
[/usr/lib/python3.8/json/decoder.py](https://localhost:8080/#) in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DIRKMJK** [comment]
Based on this info it's difficult to say what may have gone wrong. Did you manage to enable LSRC2, and has the user_name you used access to the API?

**Comment by AmauryVanEspen** [comment]
Hello @DIRKMJK 
yes
base_url, user_name, password, user_id and sid for survey id are properly filed,
I'm trying to run the script from google colab,
do not know where and how to debug from this point of the script

**Comment by DIRKMJK** [comment]
I’m not familiar with colab, so I couldn’t say whether that might be an issue. One way you could explore possible problems is to copy the code from /limepy/download.py instead of importing it from `limepy`, and then add a few print statements to the code to see what’s going on. Have any responses been given to the survey yet?

**Comment by AmauryVanEspen** [comment]
Hello,
currently it work's, but i don't know why =)
could you maybe plan a call to explore together ?
Thank you
Amaury

**Comment by AmauryVanEspen** [comment]
Hello @DIRKMJK 
could you tell me how to download the structure.lss file used with your script ? (i believe this has to be done manually from the LS server)
Thank you
Amaury

**Comment by DIRKMJK** [comment]
Yes, if you go to the survey you can export the .lss file by clicking the Export button, then select the first option

**Comment by AmauryVanEspen** [comment]
Hello,
yes I know,
i'm looking for this feature through the standard API, but not sure it has
been implemented
great work anyway !

three more questions,
first, related to the compare feature,
what is the kind of input expected for category_variable ? have you got and
example with a sample data set ?

def compare(qid, category_variable, how='Valid Percent'):
    """Compare answers for groups based on category variable"""
    summaries = []
    for group in set(df[category_variable]):
        if pd.isnull(group):
            continue
        mask = list(df[category_variable] == group)
        q = Question(my_survey, qid, mask=mask)
        summary = q.summary
        if how in list(summary.columns):
            summary = summary[[how]]
        summary.columns = [group]
        summaries.append(summary)
    return pd.concat(summaries, axis=1)

# example
compare(128, "Infos répondant", how='Valid Percent')
second question about include function,
i've got an issue i do not understand : here a string has no attribute
dataframe,
[image: image.png]
It seems i missed something:
here an example of the questions sample
[image: image.png]

finally, could you suggest a great way to explore and preview the "html"
feature with a library in python to expose and get insight from the content
produced by add_table function ?

Thank you

Amaury

**Comment by DIRKMJK** [comment]
The `category_variable` represents the variable you want to group by. For example, if you have a column `country` and you want to compare results by country, pass this variable. The html code can be saved as .html file and opened with a browser

**Comment by DIRKMJK** [comment]
Since the original problem has been solved, I'll close the issue now

**Comment by AmauryVanEspen** [comment]
Hello,
could you please be more precise about the input,
is this the question title ? the question code ? or a dataframe column ?
