### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'encode'

### ISSUE THREAD

**Issue by marquicus** [DIRKMJK/limepy#3]
I'm getting the following error while trying to execute download.get_responses

~/.virtualenvs/sandbox/lib/python3.6/site-packages/limepy/download.py in get_responses(base_url, user_name, password, user_id, sid, lang, document_type, completion_status, heading_type, response_type, from_response_id, to_response_id, fields)
     84                            document_type, completion_status, heading_type,
     85                            response_type, from_response_id, to_response_id,
---> 86                            fields)
     87     release_session_key(base_url, session_key, user_id)
     88     return csv

~/.virtualenvs/sandbox/lib/python3.6/site-packages/limepy/download.py in export_responses(user_id, base_url, session_key, sid, lang, document_type, completion_status, heading_type, response_type, from_response_id, to_response_id, fields)
     39     req = requests.post(api_url, json=payload)
     40     result = req.json()['result']
---> 41     csv = base64.b64decode(result.encode()).decode('utf-8-sig')
     42     return csv
     43 

AttributeError: 'dict' object has no attribute 'encode'

**Comment by DIRKMJK** [comment]
Is it possible the error occurred when trying to download a table that doesn’t exist, for example from a survey that has not been activated yet?

**Comment by marquicus** [comment]
yep it was the case, thanks

**Comment by DIRKMJK** [comment]
good, thanks for reporting back!
