### ISSUE TITLE
Error creating Question object for Limesurvey 2.62.2

### ISSUE THREAD

**Issue by amyisard** [DIRKMJK/limepy#8]
limepy crashes when I try to create a `Question` object from my data, and I think it might be because the csv file I've downloaded isn't exactly as required.

I'm using `limepy` with a survey run through my university's Limesurvey installation for which I don't have admin access, so I can't use your download functions.  It's running LimeSurvey Version 2.62.2+170203 and I also can't update to a newer version myself.

For manual download, you say to "_Make sure to set heading type to 'code' and reponse type to 'short'_" but I don't see exactly those options. I've attached a screenshot of the options I'm given - under 'Headings' I selected 'Question code' and under 'Responses' I selected 'Answer codes'. 
<img width="621" alt="Screenshot 2020-09-14 at 16 52 16" src="https://user-images.githubusercontent.com/29375459/93101535-addc7180-f6aa-11ea-9ecb-4f3a18aeb5de.png">

I can load in a survey and print a list of the question ids, but when I try to create a `Question` object with one of the indices I have just obtained, I get `KeyError: 'QAnnotated'`. The following code is what causes the error:

```py
    csv_file = pd.read_csv('survey.csv', sep=',')
    with open('survey.lss') as survey_structure:
        my_structure = survey_structure.read()

    my_survey = Survey(csv_file, my_structure)

    question_list = my_survey.question_list
    ids = question_list['question']
    print(ids.index)
    my_question = Question(my_survey, 495090)
```

**Comment by DIRKMJK** [comment]
Hi, the settings for downloading the csv appear to be ok. I’m not sure what might cause the problem, but here are some questions that might help identify what’s going on:
- Is <code>QAnnotated</code> a correct question code in your questionnaire, and does it appear among the column names in the first row of your csv? 
- When you inspect the question list, do you get proper values in the column ‘start’ (and not -99)?
- Could you share the entire error message, showing where in the limepy code the error is caused?

**Comment by amyisard** [comment]
Thanks very much for your quick answer - it turns out I was being stupid and had loaded the wrong version of the csv, sorry! When I looked at the column names in the first row of the csv I realized what was wrong, and everything works now. Please feel free to delete this issue.

**Comment by DIRKMJK** [comment]
No problem, thanks for letting me know & happy to hear it works now. I’ll delete the issue
